### ISSUE TITLE
Bug 🐛: github actions fails when using npm

### ISSUE THREAD

**Issue by johannesschobel** [YassinEldeeb/create-prisma-generator#87]
## Bug description

When creating a new Generator, the GitHub Action Pipeline does not work

**Comment by johannesschobel** [comment]
My current setup looks like follows (note, that i am using `npm`)!

```yml
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
          - 16.x
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Top Level Dependencies
        run: npm install

      - name: Install Dependencies
        working-directory: ./packages/generator
        run: npm install

      - name: Run Tests
        working-directory: ./packages/generator
        run: npm test

  Publish:
    runs-on: ubuntu-latest
    needs:
      - Test
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org

      - name: Install Top Level Dependencies
        run: npm install

      - name: Install Dependencies
        working-directory: ./packages/generator
        run: npm install

      - name: Publish to NPM
        working-directory: ./packages/generator
        run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

Although the pipeline now runs withour failures, the package is not published to NPM.. am i missing something?
All the best

**Comment by johannesschobel** [comment]
i got it to work like this:
```yml
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
          - 16.x
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Top Level Dependencies
        run: npm install

      - name: Install Dependencies
        working-directory: ./packages/generator
        run: npm install

      - name: Run Tests
        working-directory: ./packages/generator
        run: npm test

  Publish:
    runs-on: ubuntu-latest
    needs:
      - Test
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org

      - name: Install Top Level Dependencies
        run: npm install

      - name: Install Dependencies
        working-directory: ./packages/generator
        run: npm install

      - name: Publish to NPM
        working-directory: ./packages/generator
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Semantic Release
        working-directory: ./packages/generator
        run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

i forgot the `npm publish`  step!

**Comment by YassinEldeeb** [comment]
weird I've not used `npm` for a while, but you're actually publishing it twice now with your current setup

**First publish**
```yml
      - name: Publish to NPM
        working-directory: ./packages/generator
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

**Second publish**
```yml
      - name: Semantic Release
        working-directory: ./packages/generator
        run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
